### ISSUE TITLE
Potential memory leak

### ISSUE THREAD

**Issue by PatrickvL** [abaire/nv2a_vsh_cpu#6] opened 2024-06-21 20:49 UTC
If `nv2a_vsh_parse_program()` gets called multiple times consecutively, without destroying the program in between, it will overwrite the `steps` member, which will leak the previously assigned memory pointer(s).

**Comment by abaire** [comment] 2024-06-22 00:14
Thanks for the report!

This is actually working as intended, and the requirement that the caller perform cleanup is mentioned in the comment for `nv2a_vsh_parse_program` [here]( https://github.com/abaire/nv2a_vsh_cpu/blob/d5a7308809a80e1b01b5c016127d4f1b91c8673b/src/nv2a_vsh_disassembler.h#L149)

As there are no guarantees with respect to the content of the `Nv2aVshProgram` passed into `nv2a_vsh_parse_program`, it'd be unsafe to attempt to deallocate `steps` on behalf of the caller (e.g., the pointer could be seemingly-valid uninitialized garbage).
We could provide an alternative API that allocates a new `Nv2aVshProgram` instead of populating an existing one, but if there's a worry that the caller isn't deallocating between calls to the parser, they'd probably just be leaking a few more bytes by failing to deallocate the wrapping struct as well.

I'm going to close this as working-as-intended, but if you have a suggestion for an alternative approach I'd be happy to discuss.

**Closed as not planned by abaire** 2024-06-22 00:14 UTC
